### ISSUE TITLE
1.12.2 - Only renders white image  - solved

### ISSUE THREAD

**Issue by Sarocesch** [Mysticpasta1/webdisplays#61]
hey no matter which website i go to the game only shows me a white image 

some time ago everything still worked

I hope that I can get support on 1.12.2 because it would be very important for me

![image](https://github.com/user-attachments/assets/f0981834-3c1e-41df-aba1-3de18bb7c5d5)

[latest.log](https://github.com/user-attachments/files/17357189/latest.log)

**Comment by Sarocesch** [comment]
I think this could be the reason


```
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at java.security.AccessController.doPrivileged(Native Method)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at java.security.AccessController.doPrivileged(Native Method)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at net.montoyo.mcef.utilities.Util.openStream(Util.java:353)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at net.montoyo.mcef.utilities.Util.download(Util.java:162)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at net.montoyo.mcef.utilities.Util.download(Util.java:225)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at net.montoyo.mcef.remote.RemoteConfig.readConfig(RemoteConfig.java:74)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at net.montoyo.mcef.remote.RemoteConfig.load(RemoteConfig.java:97)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at net.montoyo.mcef.client.ClientProxy.onInit(ClientProxy.java:99)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at net.montoyo.mcef.MCEF.onInit(MCEF.java:72)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[23:46:17] [Client thread/INFO]: [net.montoyo.mcef.utilities.Util:openStream:356]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by TheSystemGuy1337** [comment]
This project appears to be dead and suffers from a common issue: People shipping out code without **TESTING** it first.

**Comment by Sarocesch** [comment]
many thanks for the info

do you have any idea how i could still fix the mod 

as I need it very much

**Comment by GiantLuigi4** [comment]
Ok so
It looks like what happened is that a web server that mcef depends on (since mcef downloads binaries that are required for its functionality at runtime) went down
Meaning the files that were hosted on said web server are no longer able to be downloaded

As for a fix; I know nothing about the 1.12 version, so I’m not really able to offer one
Might be able to change something in the configs to fix it, not sure

**Comment by TheSystemGuy1337** [comment]
> Ok so It looks like what happened is that a web server that mcef depends on (since mcef downloads binaries that are required for its functionality at runtime) went down Meaning the files that were hosted on said web server are no longer able to be downloaded
> 
> As for a fix; I know nothing about the 1.12 version, so I’m not really able to offer one Might be able to change something in the configs to fix it, not sure

There might be a way to manually install CEF, but since the servers are dead we can safely say this project is also **dead.**

**Close the issue.**

**Comment by GiantLuigi4** [comment]
The newer versions of the mod rely on a different server, so no, the project is not dead

**Comment by TheSystemGuy1337** [comment]
> The newer versions of the mod rely on a different server, so no, the project is not dead

But I tried connecting to the new servers to *maybe* fetch the files directly, but was greeted with a 403 Forbidden.

I'll see if I can patch the 1.12.2 version to point to the new servers. I know absolutely NOTHING about Java, but will attempt to patch it anyway.

**Comment by TheSystemGuy1337** [comment]
Couldn't figure it out. We have to figure out how to perform a manual installation.

**Comment by Sarocesch** [comment]
1.12.2 works again but sometimes there are still interruptions 

think a certificate was expired or a server was not reachable 


thank you for the numerous answers

**Comment by TheSystemGuy1337** [comment]
> 1.12.2 works again but sometimes there are still interruptions
> 
> think a certificate was expired or a server was not reachable
> 
> thank you for the numerous answers

I did actually dig in the files and found an out of date cert. Since the servers (likely) use HTTPS, If I roll my clock back to 2020 *then* it might download. But chances are, the server that hosts CEF for this version of the mod is currently dead. If you can, get a new cert or offer manual installation options. Since you fixed it, where can I download the patched version? CurseForge, Modrinth (Modrinth, please use .zip instead of 100% proprietary .MODPACK files) or this GitHub repo? If I have to compile it from source, please offer Windows compiling instuctions.

**Comment by Sarocesch** [comment]
unfortunately it does not work again
it was only functional for a short time

**Comment by TheSystemGuy1337** [comment]
> unfortunately it does not work again it was only functional for a short time

We should probably just bundle CEF with the mod and skip the middleman entirely.

**Comment by Sarocesch** [comment]
Unfortunately, someone has to be able to do this

**Comment by jillv46** [comment]
I have this issue to but I see all the comments but since I have autism it's hard to understand it all. Is there a solution or am I screwed? I want to use the mod so bad but it's just white/blank

**Comment by Sarocesch** [comment]
Hey
Unfortunately currently no known solution 

and you are not alone many would like to use it 
but as far as I know the devs don't want to fix it in the old version anymore

**Comment by Sarocesch** [comment]
I have found a fix

Use this version of MCEF: https://github.com/CinemaMod/mcef/releases/tag/1.12.2-1.33
